### ISSUE TITLE
Adding content requires authentication - but what is the path for authentication?

### ISSUE THREAD

**Issue by shanecoughlan** [todogroup/awesome-oss-mgmt#15]
Contributing changes runs into an authentication problem. Would be good to have documentation on the expected process to get permissions.

<img width="1032" alt="screen shot 2018-02-27 at 10 48 36" src="https://user-images.githubusercontent.com/3616071/36748229-15e4d560-1bac-11e8-9b64-3045783da2c3.png">

**Comment by jparise** [comment]
Looks like this was contributed (/ addressed) via #16?

**Comment by shanecoughlan** [comment]
Addressed by proxy submission via Trevor, but path for future contributions is unclear for people using GitHub Desktop.

**Comment by jparise** [comment]
Got it. Contributions are accepted via GitHub pull requests.

I think adding a `CONTRIBUTING.md` document would be a good improvement.

**Comment by shanecoughlan** [comment]
Done!
