### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by RichardLitt** [todogroup/awesome-oss-mgmt#5]
Might be good to have a CC license file on this?

**Comment by caniszczyk** [comment]
@RichardLitt by default code is under ALv2 and docs under http://creativecommons.org/licenses/by/4.0/ so feel free to do a PR for CC-BY and we'll add it

**Comment by RichardLitt** [comment]
How by default? Is there an org-wide license which applies, somehow?

**Comment by caniszczyk** [comment]
@RichardLitt there's a default license for work produced by the TODO Group within the charter here: https://github.com/todogroup/charter

> All new inbound code contributions to TODO shall be made under the Apache License, Version 2.0 (available at http://www.apache.org/licenses/LICENSE-2.0) or an alternative OSI-approved open source license clearly identified by the contributor in the contribution in accordance with the DCO. All documentation will be contributed to and made available to TODO under the Creative Commons Attribution 4.0 International License (available athttp://creativecommons.org/licenses/by/4.0/) or an alternative OSI-approved open source license clearly identified by the contributor in the contribution in accordance with the DCO.

**Comment by RichardLitt** [comment]
Interesting! I've not seen org-wide licensing apply to all repositories before. It would be great to put stub licenses into each repository pointing to this - otherwise, people may assume that works are unlicensed. 

Thanks.
